### ISSUE TITLE
Merge changes from external forks

### ISSUE THREAD

**Issue by soygul** [soygul/NBug#3]
It might be a good idea to merge changes back from https://bitbucket.org/mayastudios/nbugx/commits/all and some other external repos where people did some nice refactorings.

**Comment by vbjay** [comment]
:+1 https://github.com/soygul/NBug/network

**Comment by vbjay** [comment]
You could also update the nuget package.

**Comment by soygul** [comment]
Done. Can't update NuGet as I don't use Windows any more.
