### ISSUE TITLE
Wrong xml .config output

### ISSUE THREAD

**Issue by mbger** [soygul/NBug#35]
Hey guys, 

first of all: that's a great project, thank you!
I used your configurator to setup my NBug.config file. I used redmine as an issue tracker and everything works like a charm. But after using that very same config lines in my own app, there were no reports sent anymore. 

After debugging your  project I found out that the auto-generated .config file adds a connection like this:

```<add name="NBug.Properties.Settings.Connection1" connectionString="Type=Redmine;ApiKey=xxxxxxxxxxxxxxxxxxxxxxxxx;ProjectId=crashltsw;Url=http://12.345.67.890/redmine/;" />```

The problem was that after reading the .config file everything was parsed correctly except the connection. I figured that there was an error with the .config file because connections are named incorrectly. 

So instead of naming it "Connection1" it should say "Destination1". 

The correct line in the .config file would be like this:
```<add name="NBug.Properties.Settings.Destination1" connectionString="Type=Redmine;ApiKey=xxxxxxxxxxxxxxxxxxxxxxxxx;ProjectId=crashltsw;Url=http://12.345.67.890/redmine/;" />```

Everything worked as expected after changing the connection's name. 

Best,
m

**Comment by soygul** [comment]
I think this might be a solution: https://github.com/soygul/NBug/issues/52#issuecomment-106063769

If so, let me know and I'll close the issue and update docs accordingly.

**Comment by soygul** [comment]
I'm considering this issue solved by the feedback & solution provided on the related issue thread and closing this.
