### ISSUE TITLE
NBug.log hardcoded to write to assembly location

### ISSUE THREAD

**Issue by JuliusSweetland** [soygul/NBug#49]
If the application is installed to, and running from Program Files then the application must have admin rights to be able to write back to the same location. If it doesn't then NBug will cause an application crash.

To replicate:
Create a test app with NBug logging on
Copy the application to a protected location, such as program files
Run the application as a normal user (not admin)
It should crash

Possible resolution:
Add a setting to the config to define log path, or use the same path where reports are stored.

**Comment by soygul** [comment]
That feature already exists in a different form. You need to listen for the `InternalLogWritten` event and send the logs to whatever logging you're using, and set `WriteLogToDisk = false` to prevent NBug from writing directly to disk.  See this: https://github.com/soygul/NBug/blob/master/NBug/Settings.cs#L165
