### ISSUE TITLE
MySQL exception leads to invalid Exception.xml

### ISSUE THREAD

**Issue by Algorithman** [soygul/NBug#50]
V1.2.2 (nuget)

A simple duplicate id error from mysql leads to an invalid Exception.xml.

Then NBug subsequently crashes until the files is moved/deleted/renamed. This is a real showstopper.

Here is the faulty Exception.xml (part of it)
&lt;?xml version="1.0"?&gt;
&lt;SerializableException xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;
  &lt;Data&gt;
   &lt;Server Error Code&gt;1062&lt;/Server Error Code&gt; 
  &lt;/Data&gt;
  &lt;ExtendedInformation&gt;
    &lt;Number&gt;1062&lt;/Number&gt;
    &lt;ErrorCode&gt;-2147467259&lt;/ErrorCode&gt;
    &lt;HResult&gt;-2147467259&lt;/HResult&gt;
  &lt;/ExtendedInformation&gt;
  &lt;Message&gt;Duplicate entry '15' for key 'PRIMARY'&lt;/Message&gt;
  &lt;Source&gt;MySql.Data&lt;/Source&gt;
  &lt;StackTrace&gt;   bei MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   bei MySql.Data.MySqlClient.NativeDriver.GetResult(Int32&amp; affectedRow, Int64&amp; insertedId)
   bei MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32&amp; affectedRows, Int64&amp; insertedId)
   bei MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   bei MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   bei MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)

Server Error Code is obviously wrong. If you could point me in the right direction please, because i really need a fix for that.

**Comment by soygul** [comment]
It is fixed in the master branch though I didn't make a new release lately. You can compile and use it directly in your project.

**Comment by Algorithman** [comment]
thx :)

**Comment by Algorithman** [comment]
One last remark:

Building it on release off a fresh copy will fail since packages/Nbug/tools folder don't exist yet.
probably just a missing mkdir

**Comment by soygul** [comment]
Ah true, that's only created in debug mode build. Should add it for release too though. Thanks for the report.

**Comment by Algorithman** [comment]
So now a invalid zip file will be just deleted?
Where do i have to look, if i want even a faulty xml? I need the file if a error occurs, i dont mind if subject or body isnt valid in the email. the file matters more

**Comment by soygul** [comment]
When zip is invalid, there is no xml generated.

**Comment by Algorithman** [comment]
if you give me you email addy, i can send you a zip file of the mysql error where the exception.xml is invalid.
nbug fails to read it (may be a error/flaw in the xmlserializer), cancels out again and deletes the zip now.

**Comment by Algorithman** [comment]
http://www.funky-music.de/Exception_130734893532832579.zip

**Comment by soygul** [comment]
Ok never witnessed that before...

If XML is broken, only send by mail or FTP options would be available as other options like posting to a bug tracker requires parsing the file hence requires it to be valid. So a solution requires:

`try extract zip file -> zip is valid -> try parse report -> report is invalid -> check if an FTP/Email option is defined in send options -> try send file`

I think this is unnecessary complication. The core already has excess code dealing with invalid reports stuff don't think adding more workarounds for edge cases will make life easier.

**Comment by soygul** [comment]
I think a better solution would be a better handling of unserializable exceptions, especially the `Data` field which sometimes contains `unsafe` types or even atomic integers etc.

**Comment by Algorithman** [comment]
In the BugReport.cs?

**Comment by soygul** [comment]
I don't use Windows anymore so this field is always open for PRs.

`SerializableException` and `SerializableDictionary` in https://github.com/soygul/NBug/blob/master/NBug/Core/Util/Serialization/

**Comment by Algorithman** [comment]
Quick fix for spaced Keys:

Line 73 in SerializableException.cs
writer.WriteStartElement(key.ToString().Replace(" ",""));

**Comment by Algorithman** [comment]
Thx for the fast help :+1:

**Comment by soygul** [comment]
Cool. Added it in c404b5a102cdd9234b87e4afb54ba3fc21c2ba9c

Thanks!
