### ISSUE TITLE
changes

### ISSUE THREAD

**Issue by asulwer** [soygul/NBug#53]
have made some huge changes to the way your library functions.  specifically:

1.  I am using DotNetZip as the compression library instead of your hand crafted compression.  http://dotnetzip.condeplex.com

2.  created a Serializable version of System.Version for use in SerializableException (also heavily rewritten)

3.  heavily modified Settings.cs so that settings are stored\retrieved properly (the way I think it should be done) in app.config  Created custom classes inheriting from ConfigurationSection, ConfigurationElementSection, and ConfigurationElement to load from app.config.  instead of loading as xml and parsing I preferred this method as access.  its a little clunky, could be improved?!

4.  rewrote Core.Submission.Web.Mail.cs to send emails via MAPI.  basically uses the default email provider setup on users machine to send report.  was a hassle with smtp server setup and properly knowing WHO it came from.  I need to know who it came from if I have my app installed on multiple users machines.  who broke it sort of thing.

**Comment by soygul** [comment]
I guess you meant to make a pull request instead of an issue so closing this.

Also I would suggest making small local changes and submitting them as separate pull requests. Otherwise it would not be practical to review & test all changes at once.
