### ISSUE TITLE
Type conversion/Uppercase bug

### ISSUE THREAD

**Issue by deviousasti** [soygul/NBug#68]
The string builder helper outputs 'yes' while the parser looks for 'True/False'.
And property assignments are case sensitive.

UseSsl is in an incorrect case in the helper.

**Comment by soygul** [comment]
Fixing these shouldn't be much work but I don't use Windows any more so any contributions would be awesome.

**Comment by soygul** [comment]
Fixed by: https://github.com/soygul/NBug/pull/78
