### ISSUE TITLE
nbug.handler threw an exception

### ISSUE THREAD

**Issue by kostiapl** [soygul/NBug#71]
Some of app's users  get error:
the type initializer for nbug.hander threw an exception:
System.TypeInitializationException
   at nbug.handler.get_UnhandledException

I use WPF application and initialize configuration programmatically:

            AppDomain.CurrentDomain.UnhandledException += NBug.Handler.UnhandledException;
            Current.DispatcherUnhandledException += NBug.Handler.DispatcherUnhandledException;

            NBug.Settings.StoragePath = NBug.Enums.StoragePath.CurrentDirectory;
            NBug.Settings.UIMode = NBug.Enums.UIMode.Full;
            NBug.Settings.UIProvider = NBug.Enums.UIProvider.WPF;
            NBug.Settings.WriteLogToDisk = true;
            NBug.Settings.ReleaseMode = false;
            NBug.Settings.MiniDumpType = NBug.Enums.MiniDumpType.Full;

**Comment by soygul** [comment]
I have no time to dig into this. If you manage to solve it and create a pull requires with a fix (if it's a problem with NBug), that would be awesome. Otherwise I have to close this.

**Comment by kostiapl** [comment]
Ok, thank for fast response. Try to found problem.

**Comment by soygul** [comment]
👍 Good luck.
