### ISSUE TITLE
Do not eject the Microsoft Error Report form after the program crashes

### ISSUE THREAD

**Issue by chunleik** [soygul/NBug#86]
When the program crash, only the user-defined error report form pops up, and then the program can be shut down and no more forms will pop up, such as Microsoft's Error reporting form. 
Like this

![image](https://user-images.githubusercontent.com/12792499/35184989-c236dbe8-fe37-11e7-893f-eca4e1e53b71.png)

**Comment by soygul** [comment]
This is the expected behavior.

You might try rethrowing errors to trigger further dialogs though. Check out https://github.com/soygul/NBug/blob/master/NBug/Settings.cs
