### ISSUE TITLE
Is the NuGet package supported? Is master assumed to be stable when building?

### ISSUE THREAD

**Issue by cemulate** [soygul/NBug#87]
The NuGet package looks like it stopped being updated in 2013, while this project appears to have been developed well into 2017.

The README suggests to build the DLL myself, but there's no tags or releases - is it assumed that the `master` branch will always produce a stable build?

Is there a reason the NuGet package is so old?

**Comment by soygul** [comment]
Yes master is always stable. I stopped using Windows so can't update the nuget package any more. Last published version on nuget is still rock solid but master has many improvements on top of it so I would suggest compiling it yourself.
