### ISSUE TITLE
Protocols.cs license question

### ISSUE THREAD

**Issue by hrieke** [soygul/NBug#92]
Hi,

The file Submission/Protocols.cs still contains the LGPL license header.  Is this a mistake or oversight?
If not, how does it impact with the rest of the files being MIT Licensed?
Thanks

**Comment by soygul** [comment]
It's a leftover from the early releases which was under LGPL. Fixed it now. Thanks for the notice.

https://github.com/soygul/NBug/commit/b1aa9122404efa55f7304b867a601494c42d8a30
